data:
    dataset: "celebahq"
    category: null
    image_size: 256
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 8 #matches our mobile lab setup
    num_classes: 1

model:
    model_type: "p2-weighing"
    is_upsampling: false #matches p2w
    image_size: 256
    in_channels: 3 #matches p2w
    model_channels: 128 #matches num_channels in p2w
    out_channels: 6 #matches p2w
    num_res_blocks: 1 #matches p2w
    attention_resolutions: 16 #matches p2w
    dropout: 0.0 #matches p2w
    channel_mult: [1, 1, 2, 2, 4, 4] #matches p2w
    conv_resample: true
    dims: 2
    num_classes: null
    use_checkpoint: false
    use_fp16: true #matches our p2w checkpoint 
    num_heads: 1 #matches p2w
    num_head_channels: 64 #matches p2w
    num_heads_upsample: -1
    use_scale_shift_norm: true #matches p2w
    resblock_updown: true #matches p2w
    use_new_attention_order: false #matches p2w
    var_type: fixedlarge #matches p2w
    ema: true #matches p2w
    ema_rate: 0.9999 #matches p2w
    ckpt_dir: "~/ddpm_ckpt/bedroom/lsun_bedroom.pt"

diffusion: #all matches p2w
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    total_N: 1000
    batch_size: 50
    last_only: True
    fid_stats_dir: "fid_stats/VIRTUAL_lsun_bedroom256.npz"
    fid_total_samples: 50000
    fid_batch_size: 1000
    cond_class: false
    classifier_scale: 0.0
